{% set version = "3.3.3" %}

package:
  name: robotframework-tidy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-tidy/robotframework-tidy-{{ version }}.tar.gz
  sha256: adb552c66d4be7d49d083f74a63557a08069f0ca201ba969a3b54d53640fd365

build:
  number: 0
  noarch: python
  entry_points:
    - robotidy=robotidy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1.2
    - colorama >=0.4.3
    - pathspec >=0.9.0,<0.10.0
    - python >=3.7
    - rich-click >=1.4,<1.5
    - robotframework >=4.0
    - tomli >=2.0.0

test:
  imports:
    - robotidy
  commands:
    - pip check
    - robotidy --help
  requires:
    - pip

about:
  home: https://github.com/MarketSquare/robotframework-tidy
  summary: Code autoformatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
