{% set version = "4.2.0" %}

package:
  name: robotframework-tidy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-tidy/robotframework-tidy-{{ version }}.tar.gz
  sha256: fb9c876f3418e754d1659ef9c806ba3e45366a2e9c00a4a2ae16058c2a9153bc

build:
  number: 0
  noarch: python
  entry_points:
    - robotidy=robotidy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=8.1.3
    - colorama >=0.4.3
    - jinja2 >=3.0,<4.0
    - pathspec >=0.9.0,<0.12.0
    - python >=3.7
    - rich-click >=1.4,<1.5
    - robotframework >=4.0
    - tomli >=2.0.0

test:
  imports:
    - robotidy
  commands:
    - pip check
    - robotidy --help
  requires:
    - pip

about:
  home: https://github.com/MarketSquare/robotframework-tidy
  summary: Code autoformatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
