{% set version = "4.8.0" %}

package:
  name: robotframework-tidy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-tidy/robotframework-tidy-{{ version }}.tar.gz
  sha256: 557d4b44f62a69ef20ba18fd5d85a367277a91d815233a1d5ef00ac004512a72

build:
  number: 0
  noarch: python
  entry_points:
    - robotidy=robotidy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=8.1.3,<8.2
    - colorama >=0.4.3,<0.4.7
    - jinja2 >=3.0,<4.0
    - pathspec >=0.9.0,<0.12.2
    - python >=3.7
    - rich-click >=1.4,<1.7.3
    - robotframework >=4.0
    - tomli >=2.0.0,<2.1

test:
  imports:
    - robotidy
  commands:
    - pip check
    - robotidy --help
  requires:
    - pip

about:
  home: https://github.com/MarketSquare/robotframework-tidy
  summary: Code autoformatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
